# Generated by Django 3.2.15 on 2022-10-16 12:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('type', models.CharField(choices=[('income', 'Прихід'), ('outcome', 'Розхід')], max_length=10, verbose_name='Прихід/Розхід')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Од. вим.')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва компанії')),
                ('information', models.TextField(verbose_name='Інформація')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('manager', 'Менеджер'), ('accountant', 'Бухгалтер'), ('electrician', 'Електрик'), ('plumber', 'Сантехнік'), ('owner', 'Власник')], default='user', max_length=40)),
                ('statistic_access', models.BooleanField(default=False)),
                ('checkout_access', models.BooleanField(default=False)),
                ('receipt_access', models.BooleanField(default=False)),
                ('bill_access', models.BooleanField(default=False)),
                ('flat_access', models.BooleanField(default=False)),
                ('owner_access', models.BooleanField(default=False)),
                ('building_access', models.BooleanField(default=False)),
                ('message_access', models.BooleanField(default=False)),
                ('master_apply_access', models.BooleanField(default=False)),
                ('counter_access', models.BooleanField(default=False)),
                ('site_management_access', models.BooleanField(default=False)),
                ('service_access', models.BooleanField(default=False)),
                ('tariff_access', models.BooleanField(default=False)),
                ('role_access', models.BooleanField(default=False)),
                ('user_access', models.BooleanField(default=False)),
                ('payment_requisite_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_counters', models.BooleanField(default=True, verbose_name='Показувати в рахунок')),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.measurementunit')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва тарифу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редагування')),
            ],
        ),
        migrations.CreateModel(
            name='TariffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('currency', models.CharField(max_length=55, verbose_name='Валюта')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.service', verbose_name='Послуга')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.tariff')),
            ],
        ),
        migrations.AddField(
            model_name='tariff',
            name='service_tariff',
            field=models.ManyToManyField(through='configuration.TariffService', to='configuration.Service'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=200, verbose_name='Прізвище')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='users/logos/', verbose_name='Лого')),
                ('father', models.CharField(blank=True, max_length=200, null=True, verbose_name='По батькові')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('viber', models.CharField(blank=True, max_length=200, null=True, verbose_name='Viber')),
                ('telegram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('active', 'Активний'), ('disconnected', 'Відключений')], max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(verbose_name='Нотатки')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.role', verbose_name='Роль')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
