# Generated by Django 3.2.15 on 2022-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementunit',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
