# Generated by Django 3.2.15 on 2022-10-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_measurementunit_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='none', max_length=200, verbose_name='Назва послуги'),
            preserve_default=False,
        ),
    ]
