# Generated by Django 3.2.15 on 2022-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20221021_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('director', 'Директор'), ('user', 'Користувач'), ('manager', 'Менеджер'), ('accountant', 'Бухгалтер'), ('electrician', 'Електрик'), ('plumber', 'Сантехнік'), ('owner', 'Власник')], default='user', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('active', 'Активний'), ('disconnected', 'Відключений')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
