# Generated by Django 3.2.15 on 2022-10-16 12:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_text', models.TextField(verbose_name='Короткий текст')),
                ('additional_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('additional_text', models.TextField(verbose_name='Короткий текст')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional.gallery')),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional.seo')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_photo_1', models.ImageField(upload_to='service/photos/')),
                ('service_title_1', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('service_text_1', models.TextField(verbose_name='Опис послуги')),
                ('service_photo_2', models.ImageField(upload_to='service/photos/')),
                ('service_title_2', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('service_text_2', models.TextField(verbose_name='Опис послуги')),
                ('service_photo_3', models.ImageField(upload_to='service/photos/')),
                ('service_title_3', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('service_text_3', models.TextField(verbose_name='Опис послуги')),
                ('service_photo_4', models.ImageField(upload_to='service/photos/')),
                ('service_title_4', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('service_text_4', models.TextField(verbose_name='Опис послуги')),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional.seo')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_urls', models.BooleanField(default=True, verbose_name='Показувати посилання на додатки')),
                ('slide_1', models.ImageField(upload_to='main-page/slide-photos/')),
                ('slide_2', models.ImageField(upload_to='main-page/slide-photos/')),
                ('slide_3', models.ImageField(upload_to='main-page/slide-photos/')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_text', models.TextField(verbose_name='Короткий текст')),
                ('block_header_1', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('block_description_1', models.TextField(verbose_name='Опис')),
                ('block_photo_1', models.ImageField(upload_to='main-page/block-photos/')),
                ('block_header_2', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('block_description_2', models.TextField(verbose_name='Опис')),
                ('block_photo_2', models.ImageField(upload_to='main-page/block-photos/')),
                ('block_header_3', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('block_description_3', models.TextField(verbose_name='Опис')),
                ('block_photo_3', models.ImageField(upload_to='main-page/block-photos/')),
                ('block_header_4', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('block_description_4', models.TextField(verbose_name='Опис')),
                ('block_photo_4', models.ImageField(upload_to='main-page/block-photos/')),
                ('block_header_5', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('block_description_5', models.TextField(verbose_name='Опис')),
                ('block_photo_5', models.ImageField(upload_to='main-page/block-photos/')),
                ('block_header_6', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('block_description_6', models.TextField(verbose_name='Опис')),
                ('block_photo_6', models.ImageField(upload_to='main-page/block-photos/')),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='about-us/files/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_management.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Короткий текст')),
                ('commercial_url', models.URLField(verbose_name='Посилання на комерційний сайт')),
                ('name_surname_father', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('location', models.CharField(max_length=200, verbose_name='Локація')),
                ('address', models.CharField(max_length=200, verbose_name='Адреса')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('map_code', models.TextField(verbose_name='Код карти')),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional.seo')),
            ],
        ),
    ]
