# Generated by Django 3.2.15 on 2023-01-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_1',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_3',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_4',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_5',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_6',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_header_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_header_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_header_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_header_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_header_5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_header_6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/block-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/block-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/block-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/block-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/block-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/block-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='short_text',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий текст'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='slide_1',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/slide-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='slide_2',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/slide-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='slide_3',
            field=models.ImageField(blank=True, null=True, upload_to='main-page/slide-photos/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
