# Generated by Django 3.2.15 on 2023-01-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
        ('site_management', '0003_auto_20230118_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='additional_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_gallery', to='additional.gallery'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='additional.gallery'),
        ),
    ]
