# Generated by Django 3.2.15 on 2023-01-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0004_auto_20230118_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='hello', max_length=200, verbose_name='Назва документа'),
            preserve_default=False,
        ),
    ]
