# Generated by Django 3.2.15 on 2023-01-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0005_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicefront',
            name='service_photo_1',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_photo_2',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_photo_3',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_photo_4',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_text_1',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_text_2',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_text_3',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_text_4',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_title_1',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_title_2',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_title_3',
        ),
        migrations.RemoveField(
            model_name='servicefront',
            name='service_title_4',
        ),
        migrations.CreateModel(
            name='ServiceObjectFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='service/photos/')),
                ('title', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('description', models.TextField()),
                ('service_front', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_management.servicefront')),
            ],
        ),
    ]
