# Generated by Django 3.2.15 on 2023-01-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
        ('site_management', '0006_auto_20230122_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('short_text', models.TextField(blank=True, null=True, verbose_name='Короткий текст')),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional.seo')),
            ],
        ),
        migrations.CreateModel(
            name='TariffObjectFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tariffs/photos/')),
                ('title', models.CharField(max_length=200, verbose_name='Підпис')),
                ('tariff_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_management.tariffpage')),
            ],
        ),
    ]
