# Generated by Django 3.2.15 on 2022-10-16 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('square', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площа')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('address', models.CharField(max_length=200, verbose_name='Адреса')),
                ('photo_1', models.ImageField(upload_to='houses/photos/')),
                ('photo_2', models.ImageField(upload_to='houses/photos/')),
                ('photo_3', models.ImageField(upload_to='houses/photos/')),
                ('photo_4', models.ImageField(upload_to='houses/photos/')),
                ('photo_5', models.ImageField(upload_to='houses/photos/')),
                ('user', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.flat', verbose_name='Квартира')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.house', verbose_name='Дом')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/templates')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Поверх')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.house')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('paid', 'Оплачена'), ('partly paid', 'Частково оплачена'), ('not paid', 'Не оплачена')], default='paid', max_length=20, verbose_name='Статус')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.personalaccount', verbose_name='Особовий рахунок')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.flat', verbose_name='Квартира')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.house', verbose_name='Дім')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.section', verbose_name='Секція')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.tariff', verbose_name='Тариф')),
            ],
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.section', verbose_name='Секція'),
        ),
        migrations.CreateModel(
            name='Notoriety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Сума')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('is_completed', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('outcome', 'Outcome')], default='income', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.personalaccount', verbose_name='Особовий рахунок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.articlepayment', verbose_name='Стаття')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема')),
                ('main_text', models.TextField(verbose_name='Повідомлення')),
                ('is_read', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.house')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.floor', verbose_name='Поверх'),
        ),
        migrations.AddField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.house', verbose_name='Дім'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
        migrations.AddField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.section', verbose_name='Секція'),
        ),
        migrations.AddField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.tariff', verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('null', 'Нульовий'), ('taken', 'Врахований')], max_length=10, verbose_name='Статус')),
                ('counter_evidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.flat', verbose_name='Квартира')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.house', verbose_name='Дім')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator_panel.section', verbose_name='Секція')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.tariff', verbose_name='Рахунок')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_type', models.CharField(choices=[('', 'Будь-який'), ('plumber', 'Сантехнік'), ('electrician', 'Електрик')], max_length=20, verbose_name='Тип майстра')),
                ('description', models.TextField(verbose_name='Опис')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in work', 'У роботі'), ('completed', 'Виконана')], max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.flat', verbose_name='Квартира')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
        ),
    ]
