# Generated by Django 3.2.15 on 2022-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0002_auto_20221029_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='houses/photos/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='houses/photos/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='houses/photos/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='houses/photos/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='houses/photos/'),
        ),
    ]
