# Generated by Django 3.2.15 on 2022-10-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0003_auto_20221029_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='number',
            field=models.CharField(default='none', max_length=255, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
