# Generated by Django 3.2.15 on 2022-10-31 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0004_personalaccount_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='house',
        ),
        migrations.RemoveField(
            model_name='personalaccount',
            name='section',
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.flat', verbose_name='Квартира'),
        ),
    ]
