# Generated by Django 3.2.15 on 2022-10-31 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0005_auto_20221031_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator_panel.flat', verbose_name='Квартира'),
        ),
    ]
