# Generated by Django 3.2.15 on 2022-11-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0008_auto_20221101_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator_panel.flat', verbose_name='Квартира'),
        ),
    ]
