# Generated by Django 3.2.15 on 2022-11-05 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0010_alter_personalaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
