# Generated by Django 3.2.15 on 2022-11-07 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0011_alter_flat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='house',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='section',
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Період з'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Період по'),
        ),
    ]
