# Generated by Django 3.2.15 on 2022-11-11 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_user_created_at'),
        ('administrator_panel', '0012_auto_20221107_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='house',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='section',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='tariff',
        ),
        migrations.AddField(
            model_name='evidence',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evidence',
            name='number',
            field=models.CharField(default=2000, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configuration.service', verbose_name='Рахунок'),
            preserve_default=False,
        ),
    ]
