# Generated by Django 3.2.15 on 2022-11-14 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0015_receiptservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='flat',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
