# Generated by Django 3.2.15 on 2022-11-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0016_auto_20221114_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='number',
            field=models.CharField(default='null', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
