# Generated by Django 3.2.15 on 2022-11-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_user_created_at'),
        ('administrator_panel', '0018_auto_20221115_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.tariff', verbose_name='Тариф'),
        ),
    ]
