# Generated by Django 3.2.15 on 2022-11-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0019_alter_receipt_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='phone',
        ),
    ]
