# Generated by Django 3.2.15 on 2022-11-24 21:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0020_remove_receipt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notoriety',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptservices', to='administrator_panel.receipt'),
        ),
    ]
