# Generated by Django 3.2.15 on 2022-11-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0020_remove_receipt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptservice',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptservices', to='administrator_panel.receipt'),
        ),
    ]
