# Generated by Django 3.2.15 on 2022-11-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_user_created_at'),
        ('administrator_panel', '0023_alter_notoriety_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='rest',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notoriety',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.articlepayment', verbose_name='Стаття'),
        ),
    ]
