# Generated by Django 3.2.15 on 2022-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0024_auto_20221127_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='rest',
            field=models.FloatField(default=0.0),
        ),
    ]
