# Generated by Django 3.2.15 on 2022-11-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0021_alter_receiptservice_receipt'),
        ('administrator_panel', '0025_alter_personalaccount_rest'),
    ]

    operations = [
    ]
