# Generated by Django 3.2.15 on 2022-12-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0026_merge_20221128_2337'),
        ('administrator_panel', '0026_remove_personalaccount_rest'),
    ]

    operations = [
    ]
