# Generated by Django 3.2.15 on 2022-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0027_merge_20221204_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='nullable', max_length=255),
            preserve_default=False,
        ),
    ]
