# Generated by Django 3.2.15 on 2022-12-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0029_auto_20221220_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
