# Generated by Django 3.2.15 on 2022-12-23 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0030_remove_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.AddField(
            model_name='application',
            name='desired_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='desired_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notoriety',
            name='type',
            field=models.CharField(choices=[('income', 'Прихід'), ('outcome', 'Розхід')], default='income', max_length=20),
        ),
    ]
