# Generated by Django 3.2.15 on 2022-12-23 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator_panel', '0031_auto_20221223_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='owner',
        ),
        migrations.AddField(
            model_name='application',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuration.user', verbose_name='Майстер'),
            preserve_default=False,
        ),
    ]
