# Generated by Django 3.2.15 on 2022-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0032_auto_20221223_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
