# Generated by Django 3.2.15 on 2022-12-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0033_application_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='master_type',
            field=models.CharField(choices=[('', 'Будь-який спеціаліст'), ('plumber', 'Сантехнік'), ('electrician', 'Електрик')], max_length=20, verbose_name='Тип майстра'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('in work', 'У роботі'), ('completed', 'Виконана')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
