# Generated by Django 3.2.15 on 2022-12-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0035_auto_20221223_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(default='null', verbose_name='Опис'),
            preserve_default=False,
        ),
    ]
