# Generated by Django 3.2.15 on 2022-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0036_alter_application_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_by_director',
            field=models.BooleanField(default=False),
        ),
    ]
