# Generated by Django 3.2.15 on 2023-01-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_panel', '0039_auto_20221229_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_specific_owner',
            field=models.BooleanField(default=False),
        ),
    ]
